// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function GetVaultDir() {
  return window['go']['main']['App']['GetVaultDir']();
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function SetSecret(arg1, arg2) {
  return window['go']['main']['App']['SetSecret'](arg1, arg2);
}

export function VaultExists() {
  return window['go']['main']['App']['VaultExists']();
}
