// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSecret(arg1:string):Promise<void>;

export function GetSecret(arg1:string):Promise<main.SecretEntry>;

export function GetVaultDir():Promise<string>;

export function ListSecretNames():Promise<Array<string>>;

export function ListSecrets():Promise<Array<main.SecretEntry>>;

export function SetSecret(arg1:string,arg2:Record<string, string>):Promise<void>;

export function VaultExists():Promise<boolean>;
